"""
Metadata reader for Zarr cube datasets.

This module provides utilities to read metadata from unified training_metadata.csv
and construct paths to synthetic and real Zarr cubes for training.
"""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import pandas as pd


@dataclass
class CubeROI:
    """Represents a single cube ROI with metadata."""

    prepared_id: int
    output_folder: str
    tile_name: str
    cube_size: int
    z_start: int
    y_start: int
    x_start: int
    z_end: int
    y_end: int
    x_end: int
    time_size: int
    channel_size: int
    server_folder: str
    data_location: str
    is_synthetic: bool
    synthetic_cube_path: Optional[str] = None
    real_cube_path: Optional[str] = None

    def __post_init__(self):
        """Construct cube paths after initialization."""
        if self.synthetic_cube_path is None:
            self.synthetic_cube_path = self._get_synthetic_path()
        if self.real_cube_path is None:
            self.real_cube_path = self._get_real_path()

    def _get_synthetic_path(self) -> str:
        """Construct path to synthetic cube."""
        return os.path.join(
            self.server_folder, self.output_folder, self.tile_name
        )

    def _get_real_path(self) -> str:
        """Construct path to real cube."""
        return os.path.join(
            self.data_location, self.output_folder, self.tile_name
        )


def load_training_metadata(
    csv_path: str,
    filter_synthetic: Optional[bool] = None,
    max_rois: Optional[int] = None,
) -> pd.DataFrame:
    """
    Load unified training metadata from a single CSV file.
    
    Args:
        csv_path: Path to training_metadata.csv (must be generated by prepare_synthetic_metadata.py)
        filter_synthetic: If True, only return synthetic entries. If False, only real.
                         If None, return all entries.
        max_rois: Maximum number of rows to return. If None, return all.
        
    Returns:
        DataFrame with unified metadata schema
    """
    csv_path_obj = Path(csv_path)
    
    if not csv_path_obj.exists():
        raise FileNotFoundError(f"training_metadata.csv not found at {csv_path}")
    
    df = pd.read_csv(csv_path)
    
    # Validate required columns
    required_cols = [
        "prepared_id", "tile_name", "output_folder", "server_folder",
        "z_start", "y_start", "x_start", "z_end", "y_end", "x_end",
        "z_size", "y_size", "x_size", "time_size", "channel_size",
        "is_synthetic", "synthetic_cube_path"
    ]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(
            f"Missing required columns in training_metadata.csv: {missing_cols}"
        )
    
    # Filter by synthetic flag if requested
    if filter_synthetic is not None:
        mask: pd.Series = df["is_synthetic"] == filter_synthetic
        df = df.loc[mask].copy()
    
    # Limit number of rows if requested
    if max_rois is not None:
        df = df.iloc[:max_rois].copy()
    
    # Ensure we return a DataFrame
    result: pd.DataFrame = df
    return result


def get_roi_list(
    df: pd.DataFrame,
    use_synthetic: bool = True,
    check_exists: bool = True,
    max_rois: Optional[int] = None,
) -> List[CubeROI]:
    """
    Convert metadata DataFrame to list of CubeROI objects.

    Args:
        df: DataFrame from load_training_metadata (unified CSV format)
        use_synthetic: If True, use synthetic cube paths. If False, use real.
        check_exists: If True, verify that cube files exist before including.
        max_rois: Maximum number of ROIs to return. If None, return all valid ROIs.

    Returns:
        List of CubeROI objects.
    """
    roi_list = []

    for _, row in df.iterrows():
        # Use pre-computed paths from unified CSV
        if use_synthetic:
            cube_path = str(row["synthetic_cube_path"])
        else:
            real_path_val = row.get("real_cube_path")
            if real_path_val is not None and pd.notna(real_path_val):
                cube_path = str(real_path_val)
            else:
                cube_path = None

        if cube_path is None:
            continue

        if check_exists and not os.path.exists(cube_path):
            continue

        # Handle data_location - may be NaN in unified format
        data_location_val = row.get("data_location", "")
        try:
            if data_location_val is None:
                data_location = ""
            elif isinstance(data_location_val, (float, type(pd.NA))):
                if pd.isna(data_location_val):  # type: ignore
                    data_location = ""
                else:
                    data_location = str(data_location_val)
            else:
                data_location = str(data_location_val)
        except (ValueError, TypeError):
            data_location = ""

        # Handle cube_size with proper None handling
        cube_size_val = row.get("cube_size")
        if cube_size_val is None or pd.isna(cube_size_val):
            cube_size_val = row.get("z_size", 128)
        cube_size = int(cube_size_val) if cube_size_val is not None and not pd.isna(cube_size_val) else 128

        roi = CubeROI(
            prepared_id=int(row["prepared_id"]),
            output_folder=str(row["output_folder"]),
            tile_name=str(row["tile_name"]),
            cube_size=cube_size,
            z_start=int(row["z_start"]),
            y_start=int(row["y_start"]),
            x_start=int(row["x_start"]),
            z_end=int(row["z_end"]),
            y_end=int(row["y_end"]),
            x_end=int(row["x_end"]),
            time_size=int(row["time_size"]),
            channel_size=int(row["channel_size"]),
            server_folder=str(row["server_folder"]),
            data_location=str(data_location),
            is_synthetic=bool(row["is_synthetic"]),
        )

        roi_list.append(roi)
        
        # Stop if we've reached the maximum
        if max_rois is not None and len(roi_list) >= max_rois:
            break

    return roi_list


def get_paired_roi_lists(
    csv_path: str, check_exists: bool = True, max_rois: Optional[int] = None
) -> tuple[List[CubeROI], List[CubeROI]]:
    """
    Get paired lists of synthetic and real ROIs from unified CSV.

    This ensures that both lists have the same ROI indices in the same order,
    so training on synthetic[0] corresponds to training on real[0] for the same ROI.

    Args:
        csv_path: Path to training_metadata.csv
        check_exists: If True, verify that cube files exist
        max_rois: Maximum number of ROI pairs to return. If None, return all valid pairs.

    Returns:
        Tuple of (synthetic_roi_list, real_roi_list)
    """
    # Load all metadata
    df = load_training_metadata(csv_path, filter_synthetic=None)

    # Group by output_folder and tile_name to find matching pairs
    synthetic_rois = []
    real_rois = []
    grouped = df.groupby(["output_folder", "tile_name"])

    for group_key, group in grouped:
        if isinstance(group_key, tuple) and len(group_key) == 2:
            output_folder, tile_name = group_key
        else:
            # Fallback if groupby returns something unexpected
            continue
        is_synthetic_mask = group["is_synthetic"] == True  # noqa: E712
        synthetic_rows = group[is_synthetic_mask]
        real_rows = group[~is_synthetic_mask]

        if len(synthetic_rows) == 0 or len(real_rows) == 0:
            continue

        # Take first synthetic and first real entry
        synth_row = synthetic_rows.iloc[0]
        real_row = real_rows.iloc[0]

        # Use pre-computed paths
        synth_path = str(synth_row["synthetic_cube_path"])
        real_path = str(real_row["real_cube_path"]) if pd.notna(real_row.get("real_cube_path")) else None

        if check_exists:
            if not os.path.exists(synth_path):
                continue
            if real_path is None or not os.path.exists(real_path):
                continue

        # Create ROI objects
        synth_roi = CubeROI(
            prepared_id=int(synth_row["prepared_id"]),
            output_folder=str(synth_row["output_folder"]),
            tile_name=str(synth_row["tile_name"]),
            cube_size=int(synth_row.get("cube_size", synth_row.get("z_size", 128))),
            z_start=int(synth_row["z_start"]),
            y_start=int(synth_row["y_start"]),
            x_start=int(synth_row["x_start"]),
            z_end=int(synth_row["z_end"]),
            y_end=int(synth_row["y_end"]),
            x_end=int(synth_row["x_end"]),
            time_size=int(synth_row["time_size"]),
            channel_size=int(synth_row["channel_size"]),
            server_folder=str(synth_row["server_folder"]),
            data_location=str(synth_row.get("data_location", "")),
            is_synthetic=True,
        )

        real_roi = CubeROI(
            prepared_id=int(real_row["prepared_id"]),
            output_folder=str(real_row["output_folder"]),
            tile_name=str(real_row["tile_name"]),
            cube_size=int(real_row.get("cube_size", real_row.get("z_size", 128))),
            z_start=int(real_row["z_start"]),
            y_start=int(real_row["y_start"]),
            x_start=int(real_row["x_start"]),
            z_end=int(real_row["z_end"]),
            y_end=int(real_row["y_end"]),
            x_end=int(real_row["x_end"]),
            time_size=int(real_row["time_size"]),
            channel_size=int(real_row["channel_size"]),
            server_folder=str(real_row["server_folder"]),
            data_location=str(real_row.get("data_location", "")),
            is_synthetic=False,
        )

        synthetic_rois.append(synth_roi)
        real_rois.append(real_roi)
        
        # Stop if we've reached the maximum
        if max_rois is not None and len(synthetic_rois) >= max_rois:
            break

    return synthetic_rois, real_rois

